---
# Copy this file to config.yml and fill in your credentials and other details

cf_deployment:
  deployment: "cf-deployment"
  diego_deployment: "cf"
  bosh_deployment: "no-bosh-deployment"
  services_deployment: "no-cf-services-deployment"
  micro_deployment: "bosh"
  health_screen_image: "http://<dashboard_img_url>"
  router_elb_name: "cf-router"
  domain_url: "javelinmc.com"

  backend_pagerduty: "@pagerduty-backend"
  bosh_pagerduty: "@pagerduty-bosh"
  services_pagerduty: "@pagerduty-services"
  cloudops_pagerduty: "@pagerduty-cloudops"
  monitoringAndMetrics_pagerduty: "@pagerduty-monitoringAndMetrics"

  backend_email: "@<your backend email>"
  cloudops_email: "@<your cloudops email>"
  monitoringAndMetrics_email: "@<your monitoring and metrics email>"

  params: &prod_params
    expected_routes: 100
    min_deas_that_can_stage: 3
    min_reservable_stagers: 100
    smoke_timeout_secs: 360

  credentials:
    api_key: "94d0cd8b2d8ec64e96474e321273b88c"
    app_key: "9497dd7c21d5da9ef8d6e8f9b27f820a669b22b6"

  jobs: &jobs
    - appdirect_gateway
    - cloud_controller
    - collector
    - dea_next
    - health_manager
    - login
    - nats
    - router
    - syslog_aggregator
    - uaa
